# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: bash -c "
      python manage.py makemigrations blog plants users
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
#    environment:
#      - DATABASE_URL=postgresql://siavi@db:5432/postgres
    volumes:
#      - ./Gardening3:/Gardening3
       - .:/usr/src/Gardening3
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - "8000:8000"
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - pgdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdb-data: